### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by YahiaJabeur** [zoontek/react-native-dev-menu#31] opened 2022-05-12 22:07 UTC
### Bug summary

by adding use_frameworks! to the pod file, I faced this issue in the iOS project
```
 Undefined symbols for architecture x86_64
> Symbol: _OBJC_CLASS_$_FIRAnalytics
> Referenced from: objc-class-ref in RNFBAnalyticsModule.o
```

Note:
the below solution didn't fix the issue
```
$static_libs = ['RNDevMenu']

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if $static_libs.include?(pod.name)
      puts "Flag #{pod.name} as static_library"
      def pod.build_type;
         Pod::BuildType.static_library # >= 1.9
      end
    end
  end
end
```

### Library version

4.0.2

### Environment info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 215.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.24.2 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /Users/flc_user/.rvm/gems/ruby-2.6.8/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: Chipmunk 2021.2.1 Chipmunk 2021.2.1
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^6.1.0 => 6.1.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
    react-native-macos: Not Found
```

### Steps to reproduce

1. add use_frameworks! to project
2. pod install
3. npm run ios

### Reproducible sample code

```js
use_frameworks!
```

**Comment by zoontek** [comment] 2022-05-12 22:56
Duplicate of https://github.com/zoontek/react-native-dev-menu/issues/17

**Closed by zoontek** 2022-05-12 22:56 UTC
Labels: bug
